//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characters
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdDeity { get; set; }
        public int IdMythology { get; set; }
        public string Mythology { get; set; }
        public string Myth { get; set; }
        public int IdMyth { get; set; }
    
        public virtual Deity Deity { get; set; }
    }
}
