//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquivalentDeities
    {
        public int Id { get; set; }
        public int IdDeity { get; set; }
        public string EquivalentDeityName { get; set; }
        public Nullable<int> EquivalentDeityId { get; set; }
    
        public virtual Deity Deity { get; set; }
    }
}
