//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquivalentMyths
    {
        public int Id { get; set; }
        public int IdMyth { get; set; }
        public string EquivalentMyth { get; set; }
        public Nullable<int> EquivalentMythId { get; set; }
    
        public virtual Myth Myth { get; set; }
    }
}
